// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/apiclient/repository/repository.proto

package repository

// ... (rest of the generated file remains unchanged)

type RepoQuery struct {
	Repo                 string   `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	ForceRefresh         string   `protobuf:"bytes,2,opt,name=forceRefresh,proto3" json:"forceRefresh,omitempty"`
	Project              string   `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepoQuery) Reset()         { *m = RepoQuery{} }
func (m *RepoQuery) String() string { return proto.CompactTextString(m) }
func (*RepoQuery) ProtoMessage()    {}
func (*RepoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a2b2b2b2b2b2b2b, []int{0}
}

func (m *RepoQuery) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *RepoQuery) GetForceRefresh() string {
	if m != nil {
		return m.ForceRefresh
	}
	return ""
}

func (m *RepoQuery) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

// ... (rest of the generated file remains unchanged)